### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by FabSugandhi** [FabSugandhi/KasunFabianRyley_T3A2-A#12]
1. Unit Testing
- Test individual components and functions
- Ensure that user authentication, booking, and payment process works correctly

2. Integration Testing
- Test the interactions between different parts of the application

3. User Acceptance Testing (UAT)
- Conduct testing with real (or simulated) users to gather feedback
- Make adjustments based on user experience

4. Performance Testing
- Test edge cases to ensure the app performs well under different loads

**Comment by Reyleth** [comment]
Will start on testing in the back end today
