### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by FabSugandhi** [FabSugandhi/KasunFabianRyley_T3A2-A#13]
1. Prepare for Deployment
- Choose a hosting provider
- Set up continuous integration and deployment

2. Deploy the Application
- Deploy the web app to the chosen hosting environment
- Set up domain names and security certificates

3. Monitoring and Maintenance
- Implement monitoring tools to track perfomance and errors
- Setup plan for regular updates and maintenance

**Comment by Reyleth** [comment]
Back End API: https://fighttrack-abws.onrender.com

**Comment by Reyleth** [comment]
Front End: https://fighttrack.xyz/
