### ISSUE TITLE
Dataflow Diagram

### ISSUE THREAD

**Issue by FabSugandhi** [FabSugandhi/KasunFabianRyley_T3A2-A#2]
1. Define the System, Scope, and Drawing Tools
 
2. List Components of the Data Flow Diagram- Processes: Identify key actions and functions (e.g., "Class Bookings")
- Data Stores: Identify where data is stored (e.g., "Member Database") 
- Entities: Identify who or what interacts with the system (e.g., "Members")
- Data Flows: Determine how data moves between components

3. Draw a Context Diagram (Level 0)
- Draw a single process box that represents the whole system
- Add the entities involved around the process
- Connect the entities to the process with arrows to show data flow

4. Create a Level 1 Diagram
- Break the main process into smaller sub-processes
- Add data stores that the processes interact with
- Draw arrows to show how data flows between processes, data stores, and entities

5. Review and Refine
- Check for accuracy
- Get feedback

**Comment by Reyleth** [comment]
# Level 0

![level0dfd](https://github.com/user-attachments/assets/8b6a4b73-f3c5-4232-8a7b-8b8e2e29d1cd)

# Level 1

![level1dfd](https://github.com/user-attachments/assets/0fdf2e45-797a-4e07-a084-92fd0f6d979f)

## Entities:

- Member: Users who sign up, book classes, make payments, and view their dashboard.
- Owner: Manages classes and performs administrative tasks.

## Processes:

- User Authentication: Handles user signup, login, and profile management.
- Class Management: Manages class schedules and availability.
- Class Booking: Allows users to book classes based on availability.
- Payment Processing: Handles payment for different packages.
- User Dashboard: Allows users to view their class bookings, payment status, and manage their profiles.

## Database:

- Member Database: Stores member details.
- Class Schedule Database: Stores class schedules and details.
- Booking Database: Stores class bookings made by members.
- Payment Database: Stores payment information for memberships and any day passes
