### ISSUE TITLE
Application Architecture Diagram

### ISSUE THREAD

**Issue by FabSugandhi** [FabSugandhi/KasunFabianRyley_T3A2-A#3]
1. Identify Components
List the Main Parts:
- User Interfaces: How users interact with the app (e.g., Web App)
- Application Services: Core functionalities (e.g., Class Bookings)
- Data Storage: Where the data is kept (e.g., Databases)
- External Systems: Third-party services (e.g., Payment Gateway)

2. Choose Your Diagram Type
- High-Level Diagram: Shows the big picture of how the components interact
- Detailed Diagram: Provides more specific details about each component

3. Choose Diagramming Tools

4. Draw the Diagram

a. High-Level Diagram
- Draw the main components (User Interface, Application Services, Data Storage, External Systems
- Connect the components (using arrows to show how data flows)

b. Detailed Diagram:
- Break down main components (draw separate boxes for its parts)
- Show internal connections (using arrows to show how the services interact with each other and with the Database)

5. Review and Refine
- Check for accuracy
- Get feedback

**Comment by Reyleth** [comment]
![application_diagram](https://github.com/user-attachments/assets/5a6864c9-7073-4832-8754-0f28bbaa274a)

In the front end of our project React will handle the UI rendering while HTML, CSS and Javascript will be the foundational languages used to structure the front end web application. Vite will also be used to streamline development to get our front functioning as efficiently as possible. Netlify will be used to host our front end for deployment.

As the user interacts with the front end it will make HTTP requests to the back end of our application which in turn will reply with an API response.

Node js and Express js will handle the incoming HTTP requests from the front end and properly route them to the appropriate controller or middleware, and generate the corresponding API responses. Express.js will be responsible for setting up the routes, handling middleware functions, and managing the application's logic, while Node.js will handle the server-side execution and processing of these requests. This setup ensures efficient communication between the front end and back end, allowing for a seamless user experience. Render will be used as the hosting platform for our back end as it offers hosting for dynamic web applications that fit our project. Mongoose may also be used to define schemas and models for our MongoDB database.

In our database, MongoDB will be responsible for storing and managing application data, including user information. To host this database we've opted for Atlas, a fully managed cloud service tailored specifically for MongoDB that ensure reliability.
